#!/usr/bin/env bash
# Logs into the live RocketChat container as the provisioned admin and
# writes a real authToken/userId into external Specmatic examples that
# need them, across every spec file being contract-tested (not just
# authentication.yaml -- every operation in the RocketChat REST API uses
# the same two headers). RocketChat issues a fresh admin token on every
# new container, so these example files are gitignored and regenerated by
# this script right before a test run -- never committed as static
# credentials.
#
# Only external example files are touched. No spec file is ever edited --
# they declare X-Auth-Token/X-User-Id as plain header parameters (or a
# shared $ref component with the same names), and Specmatic's
# external-examples mechanism
# (https://docs.specmatic.io/features/external_examples) is the
# spec-respecting way to supply concrete values for those headers.
set -euo pipefail

BASE_URL="${RC_BASE_URL:-http://localhost:3000}"
ADMIN_USER="${ADMIN_USERNAME:-admin}"
ADMIN_PASS="${RC_ADMIN_PASS:-SpecmaticAdmin123!}"
EXAMPLES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../examples" && pwd)"
# Examples live in per-spec subfolders (specmatic/examples/<spec-name>/),
# not a flat directory -- keeps things navigable now that coverage is
# being pushed well beyond these original 4 files, and matches Specmatic's
# own confirmed-working directory recursion under --examples=<dir>.
mkdir -p "${EXAMPLES_DIR}/authentication" "${EXAMPLES_DIR}/content-management" "${EXAMPLES_DIR}/notifications" "${EXAMPLES_DIR}/messaging" "${EXAMPLES_DIR}/statistics" "${EXAMPLES_DIR}/integrations" "${EXAMPLES_DIR}/marketplace-apps" "${EXAMPLES_DIR}/miscellaneous" "${EXAMPLES_DIR}/user-management"

login_response=$(curl -sf -X POST "${BASE_URL}/api/v1/login" \
  -H "Content-Type: application/json" \
  -d "{\"user\":\"${ADMIN_USER}\",\"password\":\"${ADMIN_PASS}\"}")

auth_token=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["authToken"])')
user_id=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["userId"])')

if [ -z "$auth_token" ] || [ -z "$user_id" ]; then
  echo "Failed to extract authToken/userId from login response" >&2
  exit 1
fi

# http-response.body here is only used to type-check this example file at
# load time (the actual test assertion compares the LIVE response against
# the spec, not against this body) -- so it's the spec's own declared
# schema shape (copied from authentication.yaml's "User profile" example),
# not a live-captured one. A live-captured body would carry undocumented
# fields (see README "Issues found and fixed") and fail this file's own
# load-time type-check for the same reason those fields fail the real test.
cat > "${EXAMPLES_DIR}/authentication/get-me.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/me",
    "method": "GET",
    "headers": {
      "X-Auth-Token": "${auth_token}",
      "X-User-Id": "${user_id}"
    }
  },
  "http-response": {
    "status": 200,
    "body": {
      "_id": "aobEdbYhXfu5hkeqG",
      "name": "Example User",
      "emails": [{ "address": "example@example.com", "verified": true }],
      "status": "offline",
      "statusConnection": "offline",
      "username": "example",
      "utcOffset": 0,
      "active": true,
      "roles": ["user", "admin"],
      "settings": { "preferences": {} },
      "customFields": { "twitter": "@userstwi" },
      "avatarUrl": "http://localhost:3000/avatar/test",
      "success": true
    }
  }
}
EOF

echo "Wrote ${EXAMPLES_DIR}/authentication/get-me.json with a live auth token/userId."

# content-management.yaml -- read-only (GET) operations. Response bodies
# below are schema shapes copied from the spec's own inline examples, same
# reasoning as get-me.json above.
cat > "${EXAMPLES_DIR}/content-management/emoji-custom-all.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/emoji-custom.all",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "emojis": [{ "_id": "6542e83aa2f73c7460e18efb", "name": "happy", "aliases": ["happy-gang"], "extension": "png", "_updatedAt": "2023-11-02T00:07:22.433Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/emoji-custom-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/emoji-custom.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "emojis": {
        "update": [{ "_id": "S5XvYppoLrLd9JvQm", "name": "teste", "aliases": [], "extension": "jpg", "_updatedAt": "2019-02-18T16:48:35.119Z" }],
        "remove": [{ "_id": "2dbVBG434dnsdh23", "name": "teste3", "aliases": [], "extension": "jpg", "_updatedAt": "2019-02-18T16:48:35.119Z" }]
      },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-sounds-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-sounds.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "sounds": [{ "_id": "65462caea2f73c7460e18f83", "name": "doremi", "extension": "mp3", "_updatedAt": "2023-11-04T11:36:14.171Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "statuses": [{ "_id": "63f61be0b000b6b6d86704c8", "name": "brb", "statusType": "away", "_updatedAt": "2023-02-22T13:42:56.811Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

# No custom sound is seeded on a fresh instance, so a real _id isn't
# available without first exercising custom-sounds.create (deferred --
# multipart/form-data upload, see README). This exercises the documented
# "not found" path instead, which is real, meaningful coverage on its own.
cat > "${EXAMPLES_DIR}/content-management/custom-sounds-getone-notfound.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-sounds.getOne",
    "method": "GET",
    "query": { "_id": "nonexistent-sound-id" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 404,
    "body": { "success": false, "error": "Custom Sound not found." }
  }
}
EOF

echo "Wrote content-management.yaml read-only examples."

# custom-user-status create/update/delete: the only content-management
# write operations that are plain JSON (not multipart/form-data uploads --
# emoji-custom.*, custom-sounds.*, assets.* all require real file content
# and are deferred, see README). A unique name avoids "name already in
# use" on repeated script runs; a real status is seeded here via a live
# call so update/delete (below) have a real _id to act on -- the create
# example below issues its OWN separate real create call when Specmatic
# runs it, under a different unique name, so it doesn't collide with this
# seeded one.
STATUS_NAME="specmatic-seed-$(date +%s)"
seed_response=$(curl -sf -X POST "${BASE_URL}/api/v1/custom-user-status.create" \
  -H "Content-Type: application/json" \
  -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"name\":\"${STATUS_NAME}\",\"statusType\":\"busy\"}")
seed_id=$(printf '%s' "$seed_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["customUserStatus"]["_id"])')

if [ -z "$seed_id" ]; then
  echo "Failed to seed a custom user status for update/delete examples" >&2
  exit 1
fi

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "name": "specmatic-create-$(date +%s)-$$", "statusType": "busy" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "customUserStatus": { "_id": "65462e97a2f73c7460e18f84", "name": "caught up", "statusType": "busy", "_updatedAt": "2023-11-04T11:44:23.366Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.update",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "_id": "${seed_id}", "name": "${STATUS_NAME}-renamed", "statusType": "away" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "customUserStatus": { "_id": "${seed_id}", "name": "${STATUS_NAME}-renamed", "statusType": "away", "_updatedAt": "2023-11-04T11:51:28.353Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "customUserStatusId": "${seed_id}" }
  },
  "http-response": {
    "status": 200,
    "body": { "success": true }
  }
}
EOF

echo "Wrote custom-user-status create/update/delete examples (seeded _id: ${seed_id})."

# notifications.yaml -- banners/push, all plain JSON/query, no file
# uploads. push.get is deferred: it needs a real message _id, which
# depends on messaging.yaml (rooms/messages) not yet exercised -- a
# cross-spec fixture dependency, not a same-file quick win like the rest.
cat > "${EXAMPLES_DIR}/notifications/banners.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners",
    "method": "GET",
    "query": { "platform": "web" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "banners": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/banners-by-id.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners/ByehQjC44FwMeiLbX",
    "method": "GET",
    "query": { "platform": "web" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "banners": [], "success": true } }
}
EOF

# Exercises the real "not found" path (no banner exists to dismiss on a
# fresh instance) -- same reasoning as custom-sounds-getone-notfound.json.
cat > "${EXAMPLES_DIR}/notifications/banners-dismiss-notfound.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners.dismiss",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "bannerId": "nonexistent-banner" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "Banner not found" } }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-info.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.info",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "pushGatewayEnabled": true, "defaultPushGateway": true, "success": true } }
}
EOF

# Real "no tokens registered" 400 -- push.token create/delete below always
# leaves zero tokens registered by the time this runs (Specmatic's own
# scenario ordering isn't guaranteed relative to this one), so this is
# the one real, reproducible outcome for this operation without a live
# push gateway.
cat > "${EXAMPLES_DIR}/notifications/push-test.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.test",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 400,
    "body": { "success": false, "error": "There are no tokens for this user [error-no-tokens-for-this-user]", "errorType": "error-no-tokens-for-this-user", "details": { "method": "push_test" } }
  }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-token-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.token",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "type": "gcm", "value": "specmatic-test-token", "appName": "specmatic-test-app" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "result": { "_id": "DMMjKG2hFoLvM2hk7", "token": { "gcm": "TOKEN" }, "appName": "RocketAPP", "userId": "52d5Rw8LT3TeDa59Z", "enabled": true, "createdAt": "2018-09-11T18:22:55.006Z", "updatedAt": "2018-09-11T18:22:55.006Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-token-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.token",
    "method": "DELETE",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "token": "specmatic-test-token" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

echo "Wrote notifications.yaml examples (push.get deferred)."

# messaging.yaml -- seed real fixtures: a message in #general, a threaded
# reply to it, and a DM room. mutate/delete operations act on these same
# real ids so every example reflects the app's actual behavior, not
# invented data. chat.delete and dm.delete run at the very end (see
# bottom of this file) since other operations here depend on the message
# and room still existing.
post_response=$(curl -sf -X POST "${BASE_URL}/api/v1/chat.postMessage" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"channel":"general","text":"specmatic test message"}')
MSG_ID=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_id"])')

reply_response=$(curl -sf -X POST "${BASE_URL}/api/v1/chat.sendMessage" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"message\":{\"rid\":\"GENERAL\",\"msg\":\"specmatic thread reply\",\"tmid\":\"${MSG_ID}\"}}")
REPLY_ID=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_id"])')

dm_response=$(curl -sf -X POST "${BASE_URL}/api/v1/dm.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"username":"admin"}')
DM_RID=$(printf '%s' "$dm_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["room"]["rid"])')

if [ -z "$MSG_ID" ] || [ -z "$REPLY_ID" ] || [ -z "$DM_RID" ]; then
  echo "Failed to seed messaging.yaml fixtures (message/reply/DM room)" >&2
  exit 1
fi

# The real "message" object RocketChat returns everywhere (postMessage,
# getMessage, search, pinned/starred lists, sync*, dm.messages, ...)
# consistently carries fields the spec doesn't document: attachments,
# mentions, channels, urls, the md markdown AST, and (on some but not all
# operations) u.name. Documented once in README as a general accepted-
# drift pattern rather than repeated per operation.
#
# IMPORTANT: unlike postMessage/getMessage which share a near-identical
# real shape, each operation below hand-duplicates its OWN "message"
# object schema in the spec, with an inconsistent property list per
# operation (getMessage declares u.name, postMessage/sendMessage don't;
# none of them declare attachments/parseUrls/md/mentions/channels/urls
# even though the real app always returns them). Confirmed empirically:
# reusing one generic real-shaped body across operations caused several
# examples below to be silently dropped at load time (schema mismatch on
# THIS file's own example, not a live-request problem) with no error
# printed even under --lenient. So this helper only emits the properties
# common to every schema checked (_id, rid, msg, ts, u._id, u.username) --
# safe everywhere, at the cost of not exercising the full real shape in
# every one of our own examples (the accepted-drift finding itself is
# already established once against postMessage's real response, see
# README, so nothing is lost by keeping the rest minimal).
msg_body() {
  local id="$1" msg="$2" ts="$3" tmid="$4"
  local tmid_field=""
  [ -n "$tmid" ] && tmid_field="\"tmid\": \"${tmid}\","
  cat <<EOF
{ "_id": "${id}", "rid": "GENERAL", ${tmid_field} "msg": "${msg}", "ts": "${ts}", "u": { "_id": "${user_id}", "username": "admin" } }
EOF
}

MSG_TS=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["ts"])')
MSG_UPDATED=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_updatedAt"])')

cat > "${EXAMPLES_DIR}/messaging/chat-getMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMessage",
    "method": "GET",
    "query": { "msgId": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" ""), "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-react.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.react",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "emoji": ":smile:" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.update",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "GENERAL", "msgId": "${MSG_ID}", "text": "specmatic test message (edited)" }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" ""), "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-followMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.followMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "mid": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unfollowMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unfollowMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "mid": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-pinMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.pinMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": {
    "status": 200,
    "body": { "message": { "_id": "seed-pin-system-msg", "t": "message_pinned", "rid": "GENERAL", "ts": "${MSG_TS}", "msg": "", "u": { "_id": "${user_id}", "username": "admin", "name": "Administrator" }, "groupable": false, "attachments": [{ "text": "specmatic test message", "author_name": "admin", "author_icon": "/avatar/admin", "ts": "${MSG_TS}", "attachments": [] }], "_updatedAt": "${MSG_UPDATED}" }, "success": true }
  }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unPinMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unPinMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-starMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.starMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unStarMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unStarMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-reportMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.reportMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "description": "specmatic test report" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-ignoreUser.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.ignoreUser",
    "method": "GET",
    "query": { "rid": "GENERAL", "userId": "${user_id}", "ignore": "true" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getPinnedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getPinnedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getStarredMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getStarredMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getDiscussions.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getDiscussions",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getMentionedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMentionedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getDeletedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getDeletedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL", "since": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

# Enterprise-gated on this (Community Edition) instance -- a real,
# legitimate license-gate response, not a bug. See README. Body has only
# error/success -- this operation's declared 400 schema doesn't include
# errorType (unlike most other operations' 400 schemas), confirmed by
# checking the spec directly after this example was silently dropped at
# load time for including it.
cat > "${EXAMPLES_DIR}/messaging/chat-getMessageReadReceipts-ee.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMessageReadReceipts",
    "method": "GET",
    "query": { "messageId": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "This is an enterprise feature [error-action-not-allowed]" } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-search.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.search",
    "method": "GET",
    "query": { "roomId": "GENERAL", "searchText": "test" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [$(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" "")] } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getURLPreview.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getURLPreview",
    "method": "GET",
    "query": { "roomId": "GENERAL", "url": "https://rocket.chat" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "urlPreview": { "url": "https://rocket.chat" } } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL", "lastUpdate": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "result": { "updated": [$(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" "")], "deleted": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getThreadsList.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getThreadsList",
    "method": "GET",
    "query": { "rid": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "threads": [$(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" "")], "count": 1, "offset": 0, "total": 1, "success": true } }
}
EOF

REPLY_TS=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["ts"])')
REPLY_UPDATED=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_updatedAt"])')

cat > "${EXAMPLES_DIR}/messaging/chat-getThreadMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getThreadMessages",
    "method": "GET",
    "query": { "tmid": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [$(msg_body "$REPLY_ID" "specmatic thread reply" "$REPLY_TS" "$MSG_ID")] } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncThreadMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncThreadMessages",
    "method": "GET",
    "query": { "tmid": "${MSG_ID}", "updatedSince": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": { "update": [$(msg_body "$REPLY_ID" "specmatic thread reply" "$REPLY_TS" "$MSG_ID")], "remove": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncThreadsList.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncThreadsList",
    "method": "GET",
    "query": { "rid": "GENERAL", "updatedSince": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "threads": { "update": [$(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" "")], "remove": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-sendMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.sendMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "message": { "rid": "GENERAL", "msg": "specmatic sendMessage test" } }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "seed-sendmessage" "specmatic sendMessage test" "$MSG_TS" ""), "success": true } }
}
EOF

echo "Wrote messaging.yaml chat.* examples."

# dm.* -- real DM room created above (self-DM, "notes to self" pattern).
cat > "${EXAMPLES_DIR}/messaging/dm-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "ims": [], "offset": 0, "total": 0, "count": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-list-everyone.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.list.everyone",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "ims": [], "offset": 0, "total": 0, "count": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-members.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.members",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "members": [{ "_id": "${user_id}", "name": "Administrator", "username": "admin", "status": "offline", "utcOffset": 0 }], "count": 1, "offset": 0, "total": 1, "success": true } }
}
EOF

# unreadsFrom omitted: the spec declares it type: string, but the real
# app returns null when there's no unread interval (confirmed by direct
# curl) -- a genuine type mismatch (see README), and including it as
# null in our own example fails THIS file's own load-time type-check
# the same way, so it's left out here (not required by the schema).
cat > "${EXAMPLES_DIR}/messaging/dm-counters.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.counters",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "joined": true, "members": 1, "unreads": 0, "msgs": 0, "latest": "${MSG_UPDATED}", "userMentions": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-messages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.messages",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

# Disabled by default on this instance -- a real, legitimate feature-flag
# response, not a bug. See README.
cat > "${EXAMPLES_DIR}/messaging/dm-messages-others-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.messages.others",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "This endpoint is disabled [error-endpoint-disabled]", "errorType": "error-endpoint-disabled", "details": { "route": "/api/v1/im.messages.others" } } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-history.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.history",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-files.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.files",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "files": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-setTopic.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.setTopic",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}", "topic": "specmatic test topic" }
  },
  "http-response": { "status": 200, "body": { "topic": "specmatic test topic", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-close.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.close",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-open.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.open",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "username": "admin" }
  },
  "http-response": { "status": 200, "body": { "room": { "t": "d", "rid": "${DM_RID}", "usernames": ["admin"] }, "success": true } }
}
EOF

# Real, legitimate validation error: blocking requires a second real user
# in the DM room, and this fixture is a self-DM ("notes to self") --
# creating a second real user account is out of scope for this pass, so
# this exercises the real error path rather than a fabricated one.
cat > "${EXAMPLES_DIR}/messaging/im-blockUser-invalidroom.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/im.blockUser",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}", "block": true }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "Invalid room [error-invalid-room]", "errorType": "error-invalid-room" } }
}
EOF

echo "Wrote messaging.yaml dm.* examples."

# autotranslate.* -- disabled workspace-wide on a fresh instance; a real,
# legitimate feature-flag response for all three operations, not a bug.
cat > "${EXAMPLES_DIR}/messaging/autotranslate-getSupportedLanguages-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/autotranslate.getSupportedLanguages",
    "method": "GET",
    "query": { "targetLanguage": "en" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "AutoTranslate is disabled." } }
}
EOF

# No example written for autotranslate.saveSettings: confirmed via direct
# curl that the real app returns 400 ("AutoTranslate is disabled.") when
# called on a fresh instance, but the spec only declares 200/401 for this
# operation -- no 400 schema exists at all, so no schema-conformant
# external example is possible without inventing a response shape. This
# is itself the finding (see README) rather than something to work around.

cat > "${EXAMPLES_DIR}/messaging/autotranslate-translateMessage-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/autotranslate.translateMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "targetLanguage": "es" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "AutoTranslate is disabled." } }
}
EOF

echo "Wrote messaging.yaml autotranslate.* examples."

# chat.delete / dm.delete last -- run only after every operation above
# that depends on the message/room still existing.
cat > "${EXAMPLES_DIR}/messaging/chat-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "GENERAL", "msgId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "_id": "${MSG_ID}", "ts": "${MSG_TS}", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

echo "Wrote messaging.yaml chat.delete/dm.delete examples (run last by Specmatic's own scenario ordering, not enforced here)."

# statistics.yaml -- statistics/statistics.list are the only 2 of 11
# operations reachable on this (Community Edition) instance; both
# schemas declare zero required fields (confirmed by reading the spec),
# so a minimal, schema-conformant body is legitimate, not a shortcut.
cat > "${EXAMPLES_DIR}/statistics/statistics.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/statistics",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "totalUsers": 1, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/statistics/statistics-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/statistics.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "statistics": [{ "totalUsers": 1 }], "count": 1, "offset": 0, "total": 1, "success": true } }
}
EOF

# All 9 engagement-dashboard.* operations are Enterprise-gated on this CE
# instance (confirmed live via curl: 400, "This is an enterprise feature
# [error-action-not-allowed]"). The spec's shared 400 schema
# (components.responses.keyError) only declares success/error -- NOT
# errorType, which the real response also carries -- so errorType is
# deliberately omitted here, same reasoning as chat.getMessageReadReceipts
# in messaging.yaml's example (an extra real field would fail this file's
# own load-time type-check against the declared schema).
for op in \
  "engagement-dashboard-users-new-users:/api/v1/engagement-dashboard/users/new-users" \
  "engagement-dashboard-users-active-users:/api/v1/engagement-dashboard/users/active-users" \
  "engagement-dashboard-users-by-time-of-day:/api/v1/engagement-dashboard/users/users-by-time-of-the-day-in-a-week" \
  "engagement-dashboard-chat-busier-hourly:/api/v1/engagement-dashboard/users/chat-busier/hourly-data" \
  "engagement-dashboard-chat-busier-weekly:/api/v1/engagement-dashboard/users/chat-busier/weekly-data" \
  "engagement-dashboard-messages-sent:/api/v1/engagement-dashboard/messages/messages-sent" \
  "engagement-dashboard-messages-origin:/api/v1/engagement-dashboard/messages/origin" \
  "engagement-dashboard-top-five-channels:/api/v1/engagement-dashboard/messages/top-five-popular-channels" \
  "engagement-dashboard-channels-list:/api/v1/engagement-dashboard/channels/list" \
; do
  fname="${op%%:*}"
  path="${op#*:}"
  cat > "${EXAMPLES_DIR}/statistics/${fname}-ee.json" <<EOF
{
  "http-request": {
    "path": "${path}",
    "method": "GET",
    "query": { "start": "2026-01-01", "end": "2026-01-31" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "This is an enterprise feature [error-action-not-allowed]" } }
}
EOF
done

echo "Wrote statistics.yaml examples (2 real, 9 Enterprise-gated)."

# integrations.yaml -- integrations.create requires event/urls
# unconditionally per its own schema (a known, already-documented spec
# defect: the field descriptions say they're only required for outgoing
# integrations, but the schema makes them unconditional) -- so every
# integration created here is a real outgoing webhook, token included
# explicitly since a fresh integration otherwise has no token and
# integrations.update's own validateOutgoingIntegration() call checks the
# REQUEST BODY's token, not the DB record's (confirmed by reading
# updateOutgoingIntegration.ts -- a real 400 "Invalid token" happens if
# the update body omits it, even when the integration already has one).
integration_response=$(curl -sf -X POST "${BASE_URL}/api/v1/integrations.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"type":"webhook-outgoing","name":"specmatic-test-integration","enabled":true,"username":"admin","channel":"#general","scriptEnabled":false,"event":"sendMessage","urls":["https://example.com/webhook"],"token":"specmatic-webhook-token-abc123"}')
INTEGRATION_ID=$(printf '%s' "$integration_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["integration"]["_id"])')

oauth_app_response=$(curl -sf -X POST "${BASE_URL}/api/v1/oauth-apps.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"name":"specmatic-oauth-app","redirectUri":"https://example.com/callback","active":true}')
OAUTH_APP_ID=$(printf '%s' "$oauth_app_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["application"]["_id"])')

if [ -z "$INTEGRATION_ID" ] || [ -z "$OAUTH_APP_ID" ]; then
  echo "Failed to seed integrations.yaml fixtures (integration/oauth app)" >&2
  exit 1
fi

cat > "${EXAMPLES_DIR}/integrations/integrations-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "type": "webhook-outgoing", "name": "specmatic-create-$(date +%s)-$$", "enabled": true, "username": "admin", "channel": "#general", "scriptEnabled": false, "event": "sendMessage", "urls": ["https://example.com/webhook"] }
  },
  "http-response": { "status": 200, "body": { "integration": { "_id": "seed-integration-create", "type": "webhook-outgoing" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/integrations-get.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.get",
    "method": "GET",
    "query": { "integrationId": "${INTEGRATION_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "integration": { "_id": "${INTEGRATION_ID}", "type": "webhook-outgoing" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/integrations-history.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.history",
    "method": "GET",
    "query": { "id": "${INTEGRATION_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "history": [], "offset": 0, "items": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/integrations-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "integrations": [{ "_id": "${INTEGRATION_ID}", "type": "webhook-outgoing" }], "offset": 0, "items": 1, "total": 1, "success": true } }
}
EOF

# Requires token in the request body itself, not just on the DB record --
# see comment above.
cat > "${EXAMPLES_DIR}/integrations/integrations-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.update",
    "method": "PUT",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "integrationId": "${INTEGRATION_ID}", "type": "webhook-outgoing", "name": "specmatic-test-integration-updated", "enabled": true, "username": "admin", "channel": "#general", "scriptEnabled": false, "event": "sendMessage", "urls": ["https://example.com/webhook"], "token": "specmatic-webhook-token-abc123" }
  },
  "http-response": { "status": 200, "body": { "integration": { "_id": "${INTEGRATION_ID}", "type": "webhook-outgoing" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/webdav-getMyAccounts.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/webdav.getMyAccounts",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "accounts": [], "success": true } }
}
EOF

# Real, reproducible behavior: removing a nonexistent webdav account is
# NOT an error -- a real 200 with deletedCount: 0, confirmed live via
# curl. No real webdav account exists to remove without a live WebDAV
# server configured (out of scope), so this exercises the real "no-op
# removal" path rather than a fabricated one.
cat > "${EXAMPLES_DIR}/integrations/webdav-removeWebdavAccount.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/webdav.removeWebdavAccount",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "accountId": "nonexistent-account-id" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/oauth-apps-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/oauth-apps.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "name": "specmatic-create-$(date +%s)-$$", "redirectUri": "https://example.com/callback", "active": true }
  },
  "http-response": { "status": 200, "body": { "application": { "_id": "seed-oauth-create", "name": "specmatic-oauth-app" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/oauth-apps-get.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/oauth-apps.get",
    "method": "GET",
    "query": { "_id": "${OAUTH_APP_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "oauthApp": { "_id": "${OAUTH_APP_ID}", "name": "specmatic-oauth-app" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/oauth-apps-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/oauth-apps.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "oauthApps": [{ "_id": "${OAUTH_APP_ID}", "name": "specmatic-oauth-app" }], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/integrations/oauth-apps-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/oauth-apps.update",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "appId": "${OAUTH_APP_ID}", "name": "specmatic-oauth-app-updated", "redirectUri": "https://example.com/callback", "active": true }
  },
  "http-response": { "status": 200, "body": { "_id": "${OAUTH_APP_ID}", "name": "specmatic-oauth-app-updated", "success": true } }
}
EOF

echo "Wrote integrations.yaml create/get/history/list/update/webdav/oauth-apps examples (integrationId: ${INTEGRATION_ID}, oauthAppId: ${OAUTH_APP_ID})."

# integrations.remove / oauth-apps.delete need their OWN, separate
# fixtures -- deleting INTEGRATION_ID/OAUTH_APP_ID here (the ones
# get/history/list/update above reference) would leave those examples
# pointing at already-deleted resources by the time Specmatic actually
# runs its test suite (a later, separate step from this script). oauth-
# apps.delete: a genuine, real spec-vs-app type mismatch -- the spec
# declares {success: boolean} (an object) but the live app returns a bare
# JSON boolean `true`, confirmed via curl. This example's body is the
# spec-conformant shape for this file's own load-time type-check (same
# reasoning as elsewhere); the real mismatch shows up as a genuine
# finding when the live test runs, not fabricated here.
integration_to_remove=$(curl -sf -X POST "${BASE_URL}/api/v1/integrations.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"type":"webhook-outgoing","name":"specmatic-test-integration-to-remove","enabled":true,"username":"admin","channel":"#general","scriptEnabled":false,"event":"sendMessage","urls":["https://example.com/webhook"],"token":"specmatic-webhook-token-remove"}')
INTEGRATION_TO_REMOVE_ID=$(printf '%s' "$integration_to_remove" | python3 -c 'import json,sys; print(json.load(sys.stdin)["integration"]["_id"])')

curl -sf -X POST "${BASE_URL}/api/v1/integrations.remove" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"integrationId\":\"${INTEGRATION_TO_REMOVE_ID}\",\"type\":\"webhook-outgoing\"}" > /dev/null

cat > "${EXAMPLES_DIR}/integrations/integrations-remove.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/integrations.remove",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "integrationId": "${INTEGRATION_TO_REMOVE_ID}", "type": "webhook-outgoing" }
  },
  "http-response": { "status": 200, "body": { "integration": { "_id": "${INTEGRATION_TO_REMOVE_ID}", "type": "webhook-outgoing" }, "success": true } }
}
EOF

oauth_app_to_delete=$(curl -sf -X POST "${BASE_URL}/api/v1/oauth-apps.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"name":"specmatic-oauth-app-to-delete","redirectUri":"https://example.com/callback","active":true}')
OAUTH_APP_TO_DELETE_ID=$(printf '%s' "$oauth_app_to_delete" | python3 -c 'import json,sys; print(json.load(sys.stdin)["application"]["_id"])')

curl -sf -X POST "${BASE_URL}/api/v1/oauth-apps.delete" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"appId\":\"${OAUTH_APP_TO_DELETE_ID}\"}" > /dev/null

cat > "${EXAMPLES_DIR}/integrations/oauth-apps-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/oauth-apps.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "appId": "${OAUTH_APP_TO_DELETE_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

echo "Wrote integrations.remove/oauth-apps.delete examples using dedicated, separate fixtures (integrationId: ${INTEGRATION_TO_REMOVE_ID}, oauthAppId: ${OAUTH_APP_TO_DELETE_ID})."

# marketplace-apps.yaml -- 5 of 13 operations are real, tractable without
# external app packages/WhatsApp/video-conference setup. Deferred (not
# fabricated): POST /api/apps (install, needs a real app package),
# public/{app-id}/incoming and public/{appId}/templateMessage (webhook/
# WhatsApp-template endpoints needing external integration config),
# api/apps/{appId} GET/DELETE (real 404 for a nonexistent app is not a
# declared status code for either operation -- an undocumented-status-
# code gap, not something an example can paper over), apps/count and
# apps/buildExternalAppRequest (already-documented missing /api prefix,
# same spec-blocker category as media-calls.state but not overlaid here
# to keep scope tight), apps/marketplace (needs real outbound internet to
# Rocket.Chat's cloud marketplace -- hung/timed out in this environment,
# confirmed not a real app bug), jitsi.update-timeout (confirmed dead --
# no matching route anywhere in apps/meteor/server, tried both
# slash and dot path-segment conventions).
cat > "${EXAMPLES_DIR}/marketplace-apps/apps-installed.json" <<EOF
{
  "http-request": {
    "path": "/api/apps/installed",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "apps": [], "success": true } }
}
EOF

# Schema declares zero properties (type: object, nothing required or
# listed) -- any shape is valid here, including the real "Could not reach
# the Marketplace" response this environment returns without outbound
# internet access.
cat > "${EXAMPLES_DIR}/marketplace-apps/apps-categories.json" <<EOF
{
  "http-request": {
    "path": "/api/apps/categories",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "success": false, "error": "Could not reach the Marketplace" } }
}
EOF

cat > "${EXAMPLES_DIR}/marketplace-apps/apps-logs.json" <<EOF
{
  "http-request": {
    "path": "/api/apps/logs",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "offset": 0, "logs": [], "count": 0, "total": 0, "success": true } }
}
EOF

# /app/{id}/logs is a media-calls.state-style missing-prefix defect --
# the spec declares this path without /api/apps; the real route is
# /api/apps/{id}/logs (verified live: the bare declared path 200s with
# the SPA HTML fallback, not real JSON -- same signature already
# documented for media-calls.state). Not fixed via a dedicated overlay
# here to keep scope tight (logged as a second candidate for that same
# upstream issue); this example targets the spec's own declared (broken)
# path, so it will show the same R1001/R1002 wrong-content-type findings
# as media-calls.state did before its overlay -- a real, honest
# reflection of the spec-blocker, not something papered over.
cat > "${EXAMPLES_DIR}/marketplace-apps/app-id-logs.json" <<EOF
{
  "http-request": {
    "path": "/app/nonexistent-app-id/logs",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "offset": 0, "logs": [], "count": 0, "total": 0, "success": true } }
}
EOF

echo "Wrote marketplace-apps.yaml examples (5 real, 8 deferred/spec-blocked -- see comment above)."

# miscellaneous.yaml -- 22 of 30 operations are real and tractable.
# Deferred (not fabricated): shield.svg (text/plain SVG body, spot-
# checked live -- 200 with real channel/name params -- not committed as
# a JSON external example), licenses.maxActiveUsers (already-documented
# missing /api/v1 prefix, third instance of that spec-blocker category),
# licenses.add (needs a real license key, out of scope), jitsi.update-
# timeout (confirmed dead, same finding as marketplace-apps.yaml),
# incoming-webhook/templateMessage (need external integration config).
#
# Real, new findings from this pass: (1) commands.run's "archive" was
# tried first and genuinely archived #general -- caught and undone via
# channels.unarchive before any other fixture broke; switched to the
# harmless "shrug" command instead. (2) No installed command on this
# instance has providesPreview: true, so commands.preview's declared 200
# is untestable without one -- its declared 400 (Command Does Not
# Provide Previews) is real, valid coverage instead. (3) email-inbox's
# real body validator (packages/rest-typings/src/v1/email-inbox.ts)
# rejects an imap.sender field the OpenAPI schema's example seemed to
# suggest -- real shape has no sender field at all. (4) email-inbox.send-
# test is declared as GET in the spec but the app registers it as POST
# (apps/meteor/server/api/v1/email-inbox.ts:222) -- a real method
# mismatch, logged as a spec-blocker candidate, not fixed here.
# (5) calendar-events.info takes a query param named `id`, not `eventId`
# (unlike update/delete, which do use eventId) -- a real, easy-to-miss
# inconsistency between sibling operations.
curl -sf -X POST "${BASE_URL}/api/v1/commands.run" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"command":"shrug","roomId":"GENERAL","params":"specmatic"}' > /dev/null

event_response=$(curl -sf -X POST "${BASE_URL}/api/v1/calendar-events.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"startTime":"2026-08-01T10:00:00.000Z","subject":"specmatic test event","description":"specmatic test"}')
EVENT_ID=$(printf '%s' "$event_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')

# Unique name/email per run (like custom-user-status above) -- email
# must be unique, so a fixed name/email fails with a real conflict on
# every rerun after the first.
INBOX_SEED_NAME="specmatic-seed-inbox-$(date +%s)-$$"
inbox_response=$(curl -sf -X POST "${BASE_URL}/api/v1/email-inbox" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"name\":\"${INBOX_SEED_NAME}\",\"email\":\"${INBOX_SEED_NAME}@example.com\",\"active\":true,\"smtp\":{\"server\":\"smtp.example.com\",\"port\":587,\"username\":\"user\",\"password\":\"pass\",\"secure\":true},\"imap\":{\"server\":\"imap.example.com\",\"port\":993,\"username\":\"user\",\"password\":\"pass\",\"secure\":true}}")
INBOX_ID=$(printf '%s' "$inbox_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["_id"])')

if [ -z "$EVENT_ID" ] || [ -z "$INBOX_ID" ]; then
  echo "Failed to seed miscellaneous.yaml fixtures (calendar event/email inbox)" >&2
  exit 1
fi

cat > "${EXAMPLES_DIR}/miscellaneous/spotlight.json" <<EOF
{
  "http-request": { "path": "/api/v1/spotlight", "method": "GET", "query": { "query": "admin" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "users": [], "rooms": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/smtp-check.json" <<EOF
{
  "http-request": { "path": "/api/v1/smtp.check", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "isSMTPConfigured": false, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/licenses-info.json" <<EOF
{
  "http-request": { "path": "/api/v1/licenses.info", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "license": { "activeModules": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/commands-list.json" <<EOF
{
  "http-request": { "path": "/api/v1/commands.list", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "commands": [{ "command": "shrug" }], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/commands-get.json" <<EOF
{
  "http-request": { "path": "/api/v1/commands.get", "method": "GET", "query": { "command": "shrug" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "command": { "command": "shrug" }, "success": true } }
}
EOF

# No command installed on this instance has providesPreview: true -- the
# declared 400 ("Command Does Not Provide Previews") is real, valid
# coverage; the 200 path is untestable without such a command installed.
cat > "${EXAMPLES_DIR}/miscellaneous/commands-preview-noprev.json" <<EOF
{
  "http-request": { "path": "/api/v1/commands.preview", "method": "GET", "query": { "command": "shrug", "roomId": "GENERAL" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 400, "body": { "success": false, "error": "Command Does Not Provide Previews [error-invalid-command]" } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/commands-run.json" <<EOF
{
  "http-request": { "path": "/api/v1/commands.run", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "command": "shrug", "roomId": "GENERAL", "params": "specmatic" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/fingerprint.json" <<EOF
{
  "http-request": { "path": "/api/v1/fingerprint", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "setDeploymentAs": "updated-configuration" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/mailer.json" <<EOF
{
  "http-request": { "path": "/api/v1/mailer", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "from": "admin@example.com", "subject": "specmatic test", "body": "specmatic test body [unsubscribe]" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/mailer-unsubscribe.json" <<EOF
{
  "http-request": { "path": "/api/v1/mailer.unsubscribe", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "_id": "nonexistent", "createdAt": "2026-01-01T00:00:00.000Z" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/method-call.json" <<EOF
{
  "http-request": { "path": "/api/v1/method.call/getUserRoles", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "message": "{\\"msg\\":\\"method\\",\\"method\\":\\"getUserRoles\\",\\"params\\":[],\\"id\\":\\"1\\"}" } },
  "http-response": { "status": 200, "body": { "message": "{}", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-list.json" <<EOF
{
  "http-request": { "path": "/api/v1/email-inbox.list", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "emailInboxes": [], "total": 0, "count": 0, "offset": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/email-inbox", "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "name": "specmatic-create-$(date +%s)-$$", "email": "specmatic-create@example.com", "active": true, "smtp": { "server": "smtp.example.com", "port": 587, "username": "user", "password": "pass", "secure": true }, "imap": { "server": "imap.example.com", "port": 993, "username": "user", "password": "pass", "secure": true } }
  },
  "http-response": { "status": 200, "body": { "_id": "seed-inbox-create", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-get.json" <<EOF
{
  "http-request": { "path": "/api/v1/email-inbox/${INBOX_ID}", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "_id": "${INBOX_ID}", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-search.json" <<EOF
{
  "http-request": { "path": "/api/v1/email-inbox.search", "method": "GET", "query": { "email": "${INBOX_SEED_NAME}@example.com" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "emailInbox": { "_id": "${INBOX_ID}" }, "success": true } }
}
EOF

# Spec declares GET; real app registers POST (email-inbox.ts:222) --
# real 400 "inbox-not-found" even against a real, existing inbox (some
# additional real-world precondition beyond existing, not investigated
# further given time budget) is still genuine, valid negative-path
# coverage for the declared 400 response.
cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-send-test.json" <<EOF
{
  "http-request": { "path": "/api/v1/email-inbox.send-test/${INBOX_ID}", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 400, "body": { "success": false, "error": "inbox-not-found" } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-list.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.list", "method": "GET", "query": { "date": "2026-08-01" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "data": [{ "_id": "${EVENT_ID}" }], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-info.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.info", "method": "GET", "query": { "id": "${EVENT_ID}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "event": { "_id": "${EVENT_ID}" }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-create.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.create", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "startTime": "2026-08-01T10:00:00.000Z", "subject": "specmatic-create-$(date +%s)-$$", "description": "specmatic test" } },
  "http-response": { "status": 200, "body": { "id": "seed-event-create", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-update.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.update", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "eventId": "${EVENT_ID}", "startTime": "2026-08-02T10:00:00.000Z", "subject": "specmatic test event updated", "description": "specmatic test updated" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-import.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.import", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "externalId": "specmatic-ext-$(date +%s)-$$", "startTime": "2026-08-03T10:00:00.000Z", "subject": "specmatic imported event", "description": "specmatic test" } },
  "http-response": { "status": 200, "body": { "id": "seed-event-import", "success": true } }
}
EOF

echo "Wrote miscellaneous.yaml examples (22 real, event: ${EVENT_ID}, inbox: ${INBOX_ID})."

# calendar-events.delete / email-inbox delete need their own, dedicated
# fixtures -- same reasoning as integrations.remove/oauth-apps.delete
# above.
event_to_delete=$(curl -sf -X POST "${BASE_URL}/api/v1/calendar-events.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"startTime":"2026-08-05T10:00:00.000Z","subject":"specmatic event to delete","description":"specmatic test"}')
EVENT_TO_DELETE_ID=$(printf '%s' "$event_to_delete" | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')

curl -sf -X POST "${BASE_URL}/api/v1/calendar-events.delete" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"eventId\":\"${EVENT_TO_DELETE_ID}\"}" > /dev/null

cat > "${EXAMPLES_DIR}/miscellaneous/calendar-events-delete.json" <<EOF
{
  "http-request": { "path": "/api/v1/calendar-events.delete", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "eventId": "${EVENT_TO_DELETE_ID}" } },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

INBOX_DELETE_SEED_NAME="specmatic-seed-inbox-delete-$(date +%s)-$$"
inbox_to_delete=$(curl -sf -X POST "${BASE_URL}/api/v1/email-inbox" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"name\":\"${INBOX_DELETE_SEED_NAME}\",\"email\":\"${INBOX_DELETE_SEED_NAME}@example.com\",\"active\":true,\"smtp\":{\"server\":\"smtp.example.com\",\"port\":587,\"username\":\"user\",\"password\":\"pass\",\"secure\":true},\"imap\":{\"server\":\"imap.example.com\",\"port\":993,\"username\":\"user\",\"password\":\"pass\",\"secure\":true}}")
INBOX_TO_DELETE_ID=$(printf '%s' "$inbox_to_delete" | python3 -c 'import json,sys; print(json.load(sys.stdin)["_id"])')

curl -sf -X DELETE "${BASE_URL}/api/v1/email-inbox/${INBOX_TO_DELETE_ID}" \
  -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" > /dev/null

cat > "${EXAMPLES_DIR}/miscellaneous/email-inbox-delete.json" <<EOF
{
  "http-request": { "path": "/api/v1/email-inbox/${INBOX_TO_DELETE_ID}", "method": "DELETE", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } },
  "http-response": { "status": 200, "body": { "_id": "${INBOX_TO_DELETE_ID}", "success": true } }
}
EOF

echo "Wrote calendar-events.delete/email-inbox.delete examples using dedicated, separate fixtures."

# user-management.yaml -- 56 operations, several genuinely risky against
# a real admin session (users.logout would kill the very token this
# script and every other example depend on; users.deleteOwnAccount would
# delete the admin account outright) -- deferred, not attempted. A real
# mistake caught and undone mid-session (see miscellaneous.yaml above)
# reinforced being extra careful here: every mutating operation below
# targets a DISPOSABLE test user created just for this, never the admin
# account whose session the rest of this script depends on.
#
# Real findings: (1) roles.create/update are Enterprise-gated on this
# instance. (2) roles.addUserToRole's spec has the exact same defect
# already documented for integrations.create -- `required` lists
# `roleName`, which isn't even a declared property (`roleId` is the real
# one). (3) users.update/resetE2EKey/resetTOTP/ldap.syncNow all require
# TOTP verification unconditionally, even though 2FA isn't actually
# enabled for this admin account -- broader instance of the pattern
# already investigated for authentication.yaml's 2FA endpoints, not
# re-investigated here given time budget; the real 400 is valid coverage.
# (4) users.createToken's real 400 ("Not authorized") reflects a missing
# server-side secret setting (API_CreateTokensForUsers_SecretURLKey),
# not something wrong with the request. (5) ldap.testConnection/syncNow
# are disabled-by-default, same category as autotranslate/SMTP elsewhere.
TESTUSER="specmatictestuser$(date +%s)-$$"
testuser_response=$(curl -sf -X POST "${BASE_URL}/api/v1/users.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"email\":\"${TESTUSER}@example.com\",\"name\":\"Specmatic Test User\",\"password\":\"SpecmaticTest123!\",\"username\":\"${TESTUSER}\"}")
TESTUSER_ID=$(printf '%s' "$testuser_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["user"]["_id"])')

if [ -z "$TESTUSER_ID" ]; then
  echo "Failed to seed user-management.yaml disposable test user" >&2
  exit 1
fi

curl -sf -X POST "${BASE_URL}/api/v1/roles.addUserToRole" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"roleId\":\"livechat-agent\",\"username\":\"${TESTUSER}\"}" > /dev/null

cat > "${EXAMPLES_DIR}/user-management/permissions-listAll.json" <<EOF
{ "http-request": { "path": "/api/v1/permissions.listAll", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "update": [{ "_id": "access-permissions" }], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/permissions-update.json" <<EOF
{ "http-request": { "path": "/api/v1/permissions.update", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "permissions": [{ "_id": "access-permissions", "roles": ["admin"] }] } }, "http-response": { "status": 200, "body": { "permissions": [{ "_id": "access-permissions" }], "success": true } } }
EOF

# roles.create/update are Enterprise-gated -- real 400, see comment above.
cat > "${EXAMPLES_DIR}/user-management/roles-create-ee.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.create", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "name": "specmatic-role-$(date +%s)-$$" } }, "http-response": { "status": 400, "body": { "success": false, "error": "This is an enterprise feature [error-action-not-allowed]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-update-ee.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.update", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "roleId": "moderator", "name": "moderator" } }, "http-response": { "status": 400, "body": { "success": false, "error": "This is an enterprise feature [error-action-not-allowed]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-list.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.list", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "roles": [{ "_id": "admin" }], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-sync.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.sync", "method": "GET", "query": { "updatedSince": "2020-01-01T00:00:00.000Z" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "roles": { "update": [{ "_id": "admin" }], "remove": [] }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-addUserToRole.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.addUserToRole", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "roleId": "livechat-agent", "username": "${TESTUSER}" } }, "http-response": { "status": 200, "body": { "role": { "_id": "livechat-agent" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-getUsersInRole.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.getUsersInRole", "method": "GET", "query": { "role": "livechat-agent" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "users": [{ "_id": "${TESTUSER_ID}" }], "total": 1, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-getUsersInPublicRoles.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.getUsersInPublicRoles", "method": "GET", "query": { "role": "admin" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "users": [{ "_id": "${user_id}" }], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/roles-removeUserFromRole.json" <<EOF
{ "http-request": { "path": "/api/v1/roles.removeUserFromRole", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "roleId": "livechat-agent", "username": "${TESTUSER}" } }, "http-response": { "status": 200, "body": { "role": { "_id": "livechat-agent" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-info.json" <<EOF
{ "http-request": { "path": "/api/v1/users.info", "method": "GET", "query": { "userId": "${TESTUSER_ID}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "user": { "_id": "${TESTUSER_ID}" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-list.json" <<EOF
{ "http-request": { "path": "/api/v1/users.list", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "users": [{ "_id": "${user_id}" }], "count": 1, "offset": 0, "total": 1, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getAvatar.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getAvatar", "method": "GET", "query": { "username": "${TESTUSER}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 307, "body": {} } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-setStatus.json" <<EOF
{ "http-request": { "path": "/api/v1/users.setStatus", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "message": "specmatic test", "status": "online" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

# Spec declares zero parameters at all for this operation -- not even
# the X-Auth-Token/X-User-Id headers every other operation requires
# (confirmed by reading the spec directly; the real app does still
# require them). A real, objective spec gap, not fixed here (frozen
# spec) -- the example below matches what's actually declared, which is
# why the real request still needs the headers even though they aren't
# validated against a declared parameter.
cat > "${EXAMPLES_DIR}/user-management/users-getStatus.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getStatus", "method": "GET", "query": { "userId": "${TESTUSER_ID}" } }, "http-response": { "status": 200, "body": { "_id": "${TESTUSER_ID}", "status": "offline", "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-setActiveStatus.json" <<EOF
{ "http-request": { "path": "/api/v1/users.setActiveStatus", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}", "activeStatus": true } }, "http-response": { "status": 200, "body": { "user": { "_id": "${TESTUSER_ID}" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getPresence.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getPresence", "method": "GET", "query": { "userId": "${TESTUSER_ID}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "presence": "offline", "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-presence.json" <<EOF
{ "http-request": { "path": "/api/v1/users.presence", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "users": [{ "_id": "rocket.cat" }], "full": true, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getPreferences.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getPreferences", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 400, "body": { "success": false, "error": "FAILED TO RETRIEVE USER PREFERENCES BECAUSE THEY HAVEN'T BEEN SET UP BY THE USER YET" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-setPreferences.json" <<EOF
{ "http-request": { "path": "/api/v1/users.setPreferences", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}", "data": { "newRoomNotification": "door" } } }, "http-response": { "status": 200, "body": { "user": { "_id": "${TESTUSER_ID}" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-forgotPassword.json" <<EOF
{ "http-request": { "path": "/api/v1/users.forgotPassword", "method": "POST", "headers": { "Content-Type": "application/json" }, "body": { "email": "${TESTUSER}@example.com" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getUsernameSuggestion.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getUsernameSuggestion", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "result": "administrator", "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getAvatarSuggestion.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getAvatarSuggestion", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "suggestions": {}, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-checkUsernameAvailability.json" <<EOF
{ "http-request": { "path": "/api/v1/users.checkUsernameAvailability", "method": "GET", "query": { "username": "someRandomName123" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "result": true, "success": true } } }
EOF

# generatePersonalAccessToken/regeneratePersonalAccessToken/resetE2EKey/
# resetTOTP/ldap.syncNow/users.update all require TOTP unconditionally --
# see comment above.
cat > "${EXAMPLES_DIR}/user-management/users-generatePAT-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.generatePersonalAccessToken", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "tokenName": "specmatic-test-token" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-regeneratePAT-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.regeneratePersonalAccessToken", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "tokenName": "specmatic-test-token" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-getPersonalAccessTokens.json" <<EOF
{ "http-request": { "path": "/api/v1/users.getPersonalAccessTokens", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "tokens": [], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-removePAT-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.removePersonalAccessToken", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "tokenName": "nonexistent-token" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-requestDataDownload.json" <<EOF
{ "http-request": { "path": "/api/v1/users.requestDataDownload", "method": "GET", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "requested": true, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-logoutOtherClients.json" <<EOF
{ "http-request": { "path": "/api/v1/users.logoutOtherClients", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-autocomplete.json" <<EOF
{ "http-request": { "path": "/api/v1/users.autocomplete", "method": "GET", "query": { "selector": "{\\"term\\":\\"admin\\"}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "items": [{ "_id": "${user_id}" }], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-removeOtherTokens.json" <<EOF
{ "http-request": { "path": "/api/v1/users.removeOtherTokens", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-listTeams.json" <<EOF
{ "http-request": { "path": "/api/v1/users.listTeams", "method": "GET", "query": { "userId": "${TESTUSER_ID}" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "teams": [], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/moderation-reportUser.json" <<EOF
{ "http-request": { "path": "/api/v1/moderation.reportUser", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}", "description": "specmatic test report" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-listByStatus.json" <<EOF
{ "http-request": { "path": "/api/v1/users.listByStatus", "method": "GET", "query": { "status": "active" }, "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 200, "body": { "users": [{ "_id": "${user_id}" }], "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/ldap-syncNow-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/ldap.syncNow", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/ldap-testConnection-disabled.json" <<EOF
{ "http-request": { "path": "/api/v1/ldap.testConnection", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" } }, "http-response": { "status": 400, "body": { "success": false, "error": "LDAP_disabled" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/avatar-subject.json" <<EOF
{ "http-request": { "path": "/api/v1/avatar/${TESTUSER}", "method": "GET" }, "http-response": { "status": 200, "body": {} } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-sendWelcomeEmail-smtp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.sendWelcomeEmail", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "email": "${TESTUSER}@example.com" } }, "http-response": { "status": 400, "body": { "success": false, "error": "SMTP is not configured [error-email-send-failed]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/sendInvitationEmail.json" <<EOF
{ "http-request": { "path": "/api/v1/sendInvitationEmail", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "emails": ["${TESTUSER}@example.com"] } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

# Same spec gap as users.getStatus above -- zero parameters declared at
# all, not even auth headers the real app requires.
cat > "${EXAMPLES_DIR}/user-management/users-sendConfirmationEmail.json" <<EOF
{ "http-request": { "path": "/api/v1/users.sendConfirmationEmail", "method": "POST", "headers": { "Content-Type": "application/json" }, "body": { "email": "${TESTUSER}@example.com" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-createToken-notauth.json" <<EOF
{ "http-request": { "path": "/api/v1/users.createToken", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}", "secret": "specmatic-test-secret" } }, "http-response": { "status": 400, "body": { "success": false, "error": "Not authorized [error-not-authorized]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-register.json" <<EOF
{ "http-request": { "path": "/api/v1/users.register", "method": "POST", "headers": { "Content-Type": "application/json" }, "body": { "username": "specmatic-create-$(date +%s)-$$", "email": "specmatic-reg-$(date +%s)-$$@example.com", "pass": "SpecmaticTest123!", "name": "Specmatic Reg User" } }, "http-response": { "status": 200, "body": { "user": { "_id": "seed-register" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-update-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.update", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}", "data": { "name": "Specmatic Test User Updated" } } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-updateOwnBasicInfo.json" <<EOF
{ "http-request": { "path": "/api/v1/users.updateOwnBasicInfo", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "data": { "name": "Administrator" } } }, "http-response": { "status": 200, "body": { "user": { "_id": "${user_id}" }, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-deactivateIdle.json" <<EOF
{ "http-request": { "path": "/api/v1/users.deactivateIdle", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "daysIdle": 36500 } }, "http-response": { "status": 200, "body": { "count": 0, "success": true } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-resetE2EKey-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.resetE2EKey", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

cat > "${EXAMPLES_DIR}/user-management/users-resetTOTP-totp.json" <<EOF
{ "http-request": { "path": "/api/v1/users.resetTOTP", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}" } }, "http-response": { "status": 400, "body": { "success": false, "error": "TOTP Required [totp-required]" } } }
EOF

echo "Wrote user-management.yaml examples (testUserId: ${TESTUSER_ID})."

# users.delete last, on the disposable test user only -- never the admin.
curl -sf -X POST "${BASE_URL}/api/v1/users.delete" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"userId\":\"${TESTUSER_ID}\"}" > /dev/null

cat > "${EXAMPLES_DIR}/user-management/users-delete.json" <<EOF
{ "http-request": { "path": "/api/v1/users.delete", "method": "POST", "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" }, "body": { "userId": "${TESTUSER_ID}" } }, "http-response": { "status": 200, "body": { "success": true } } }
EOF

echo "Wrote users.delete example, disposable test user removed. Deferred (too risky against the admin session this whole script depends on): users.logout, users.deleteOwnAccount."
