#!/usr/bin/env bash
# Logs into the live RocketChat container as the provisioned admin and
# writes a real authToken/userId into external Specmatic examples that
# need them, across every spec file being contract-tested (not just
# authentication.yaml -- every operation in the RocketChat REST API uses
# the same two headers). RocketChat issues a fresh admin token on every
# new container, so these example files are gitignored and regenerated by
# this script right before a test run -- never committed as static
# credentials.
#
# Only external example files are touched. No spec file is ever edited --
# they declare X-Auth-Token/X-User-Id as plain header parameters (or a
# shared $ref component with the same names), and Specmatic's
# external-examples mechanism
# (https://docs.specmatic.io/features/external_examples) is the
# spec-respecting way to supply concrete values for those headers.
set -euo pipefail

BASE_URL="${RC_BASE_URL:-http://localhost:3000}"
ADMIN_USER="${ADMIN_USERNAME:-admin}"
ADMIN_PASS="${RC_ADMIN_PASS:-SpecmaticAdmin123!}"
EXAMPLES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../examples" && pwd)"
# Examples live in per-spec subfolders (specmatic/examples/<spec-name>/),
# not a flat directory -- keeps things navigable now that coverage is
# being pushed well beyond these original 4 files, and matches Specmatic's
# own confirmed-working directory recursion under --examples=<dir>.
mkdir -p "${EXAMPLES_DIR}/authentication" "${EXAMPLES_DIR}/content-management" "${EXAMPLES_DIR}/notifications" "${EXAMPLES_DIR}/messaging"

login_response=$(curl -sf -X POST "${BASE_URL}/api/v1/login" \
  -H "Content-Type: application/json" \
  -d "{\"user\":\"${ADMIN_USER}\",\"password\":\"${ADMIN_PASS}\"}")

auth_token=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["authToken"])')
user_id=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["userId"])')

if [ -z "$auth_token" ] || [ -z "$user_id" ]; then
  echo "Failed to extract authToken/userId from login response" >&2
  exit 1
fi

# http-response.body here is only used to type-check this example file at
# load time (the actual test assertion compares the LIVE response against
# the spec, not against this body) -- so it's the spec's own declared
# schema shape (copied from authentication.yaml's "User profile" example),
# not a live-captured one. A live-captured body would carry undocumented
# fields (see README "Issues found and fixed") and fail this file's own
# load-time type-check for the same reason those fields fail the real test.
cat > "${EXAMPLES_DIR}/authentication/get-me.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/me",
    "method": "GET",
    "headers": {
      "X-Auth-Token": "${auth_token}",
      "X-User-Id": "${user_id}"
    }
  },
  "http-response": {
    "status": 200,
    "body": {
      "_id": "aobEdbYhXfu5hkeqG",
      "name": "Example User",
      "emails": [{ "address": "example@example.com", "verified": true }],
      "status": "offline",
      "statusConnection": "offline",
      "username": "example",
      "utcOffset": 0,
      "active": true,
      "roles": ["user", "admin"],
      "settings": { "preferences": {} },
      "customFields": { "twitter": "@userstwi" },
      "avatarUrl": "http://localhost:3000/avatar/test",
      "success": true
    }
  }
}
EOF

echo "Wrote ${EXAMPLES_DIR}/authentication/get-me.json with a live auth token/userId."

# content-management.yaml -- read-only (GET) operations. Response bodies
# below are schema shapes copied from the spec's own inline examples, same
# reasoning as get-me.json above.
cat > "${EXAMPLES_DIR}/content-management/emoji-custom-all.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/emoji-custom.all",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "emojis": [{ "_id": "6542e83aa2f73c7460e18efb", "name": "happy", "aliases": ["happy-gang"], "extension": "png", "_updatedAt": "2023-11-02T00:07:22.433Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/emoji-custom-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/emoji-custom.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "emojis": {
        "update": [{ "_id": "S5XvYppoLrLd9JvQm", "name": "teste", "aliases": [], "extension": "jpg", "_updatedAt": "2019-02-18T16:48:35.119Z" }],
        "remove": [{ "_id": "2dbVBG434dnsdh23", "name": "teste3", "aliases": [], "extension": "jpg", "_updatedAt": "2019-02-18T16:48:35.119Z" }]
      },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-sounds-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-sounds.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "sounds": [{ "_id": "65462caea2f73c7460e18f83", "name": "doremi", "extension": "mp3", "_updatedAt": "2023-11-04T11:36:14.171Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "statuses": [{ "_id": "63f61be0b000b6b6d86704c8", "name": "brb", "statusType": "away", "_updatedAt": "2023-02-22T13:42:56.811Z" }],
      "count": 1, "offset": 0, "total": 1, "success": true
    }
  }
}
EOF

# No custom sound is seeded on a fresh instance, so a real _id isn't
# available without first exercising custom-sounds.create (deferred --
# multipart/form-data upload, see README). This exercises the documented
# "not found" path instead, which is real, meaningful coverage on its own.
cat > "${EXAMPLES_DIR}/content-management/custom-sounds-getone-notfound.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-sounds.getOne",
    "method": "GET",
    "query": { "_id": "nonexistent-sound-id" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 404,
    "body": { "success": false, "error": "Custom Sound not found." }
  }
}
EOF

echo "Wrote content-management.yaml read-only examples."

# custom-user-status create/update/delete: the only content-management
# write operations that are plain JSON (not multipart/form-data uploads --
# emoji-custom.*, custom-sounds.*, assets.* all require real file content
# and are deferred, see README). A unique name avoids "name already in
# use" on repeated script runs; a real status is seeded here via a live
# call so update/delete (below) have a real _id to act on -- the create
# example below issues its OWN separate real create call when Specmatic
# runs it, under a different unique name, so it doesn't collide with this
# seeded one.
STATUS_NAME="specmatic-seed-$(date +%s)"
seed_response=$(curl -sf -X POST "${BASE_URL}/api/v1/custom-user-status.create" \
  -H "Content-Type: application/json" \
  -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"name\":\"${STATUS_NAME}\",\"statusType\":\"busy\"}")
seed_id=$(printf '%s' "$seed_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["customUserStatus"]["_id"])')

if [ -z "$seed_id" ]; then
  echo "Failed to seed a custom user status for update/delete examples" >&2
  exit 1
fi

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "name": "specmatic-create-$(date +%s)-$$", "statusType": "busy" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "customUserStatus": { "_id": "65462e97a2f73c7460e18f84", "name": "caught up", "statusType": "busy", "_updatedAt": "2023-11-04T11:44:23.366Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.update",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "_id": "${seed_id}", "name": "${STATUS_NAME}-renamed", "statusType": "away" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "customUserStatus": { "_id": "${seed_id}", "name": "${STATUS_NAME}-renamed", "statusType": "away", "_updatedAt": "2023-11-04T11:51:28.353Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/content-management/custom-user-status-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/custom-user-status.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "customUserStatusId": "${seed_id}" }
  },
  "http-response": {
    "status": 200,
    "body": { "success": true }
  }
}
EOF

echo "Wrote custom-user-status create/update/delete examples (seeded _id: ${seed_id})."

# notifications.yaml -- banners/push, all plain JSON/query, no file
# uploads. push.get is deferred: it needs a real message _id, which
# depends on messaging.yaml (rooms/messages) not yet exercised -- a
# cross-spec fixture dependency, not a same-file quick win like the rest.
cat > "${EXAMPLES_DIR}/notifications/banners.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners",
    "method": "GET",
    "query": { "platform": "web" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "banners": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/banners-by-id.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners/ByehQjC44FwMeiLbX",
    "method": "GET",
    "query": { "platform": "web" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "banners": [], "success": true } }
}
EOF

# Exercises the real "not found" path (no banner exists to dismiss on a
# fresh instance) -- same reasoning as custom-sounds-getone-notfound.json.
cat > "${EXAMPLES_DIR}/notifications/banners-dismiss-notfound.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/banners.dismiss",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "bannerId": "nonexistent-banner" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "Banner not found" } }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-info.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.info",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "pushGatewayEnabled": true, "defaultPushGateway": true, "success": true } }
}
EOF

# Real "no tokens registered" 400 -- push.token create/delete below always
# leaves zero tokens registered by the time this runs (Specmatic's own
# scenario ordering isn't guaranteed relative to this one), so this is
# the one real, reproducible outcome for this operation without a live
# push gateway.
cat > "${EXAMPLES_DIR}/notifications/push-test.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.test",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": {
    "status": 400,
    "body": { "success": false, "error": "There are no tokens for this user [error-no-tokens-for-this-user]", "errorType": "error-no-tokens-for-this-user", "details": { "method": "push_test" } }
  }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-token-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.token",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "type": "gcm", "value": "specmatic-test-token", "appName": "specmatic-test-app" }
  },
  "http-response": {
    "status": 200,
    "body": {
      "result": { "_id": "DMMjKG2hFoLvM2hk7", "token": { "gcm": "TOKEN" }, "appName": "RocketAPP", "userId": "52d5Rw8LT3TeDa59Z", "enabled": true, "createdAt": "2018-09-11T18:22:55.006Z", "updatedAt": "2018-09-11T18:22:55.006Z" },
      "success": true
    }
  }
}
EOF

cat > "${EXAMPLES_DIR}/notifications/push-token-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/push.token",
    "method": "DELETE",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "token": "specmatic-test-token" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

echo "Wrote notifications.yaml examples (push.get deferred)."

# messaging.yaml -- seed real fixtures: a message in #general, a threaded
# reply to it, and a DM room. mutate/delete operations act on these same
# real ids so every example reflects the app's actual behavior, not
# invented data. chat.delete and dm.delete run at the very end (see
# bottom of this file) since other operations here depend on the message
# and room still existing.
post_response=$(curl -sf -X POST "${BASE_URL}/api/v1/chat.postMessage" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"channel":"general","text":"specmatic test message"}')
MSG_ID=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_id"])')

reply_response=$(curl -sf -X POST "${BASE_URL}/api/v1/chat.sendMessage" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d "{\"message\":{\"rid\":\"GENERAL\",\"msg\":\"specmatic thread reply\",\"tmid\":\"${MSG_ID}\"}}")
REPLY_ID=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_id"])')

dm_response=$(curl -sf -X POST "${BASE_URL}/api/v1/dm.create" \
  -H "Content-Type: application/json" -H "X-Auth-Token: ${auth_token}" -H "X-User-Id: ${user_id}" \
  -d '{"username":"admin"}')
DM_RID=$(printf '%s' "$dm_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["room"]["rid"])')

if [ -z "$MSG_ID" ] || [ -z "$REPLY_ID" ] || [ -z "$DM_RID" ]; then
  echo "Failed to seed messaging.yaml fixtures (message/reply/DM room)" >&2
  exit 1
fi

# The real "message" object RocketChat returns everywhere (postMessage,
# getMessage, search, pinned/starred lists, sync*, dm.messages, ...)
# consistently carries fields the spec doesn't document: attachments,
# mentions, channels, urls, the md markdown AST, and (on some but not all
# operations) u.name. Documented once in README as a general accepted-
# drift pattern rather than repeated per operation.
#
# IMPORTANT: unlike postMessage/getMessage which share a near-identical
# real shape, each operation below hand-duplicates its OWN "message"
# object schema in the spec, with an inconsistent property list per
# operation (getMessage declares u.name, postMessage/sendMessage don't;
# none of them declare attachments/parseUrls/md/mentions/channels/urls
# even though the real app always returns them). Confirmed empirically:
# reusing one generic real-shaped body across operations caused several
# examples below to be silently dropped at load time (schema mismatch on
# THIS file's own example, not a live-request problem) with no error
# printed even under --lenient. So this helper only emits the properties
# common to every schema checked (_id, rid, msg, ts, u._id, u.username) --
# safe everywhere, at the cost of not exercising the full real shape in
# every one of our own examples (the accepted-drift finding itself is
# already established once against postMessage's real response, see
# README, so nothing is lost by keeping the rest minimal).
msg_body() {
  local id="$1" msg="$2" ts="$3" tmid="$4"
  local tmid_field=""
  [ -n "$tmid" ] && tmid_field="\"tmid\": \"${tmid}\","
  cat <<EOF
{ "_id": "${id}", "rid": "GENERAL", ${tmid_field} "msg": "${msg}", "ts": "${ts}", "u": { "_id": "${user_id}", "username": "admin" } }
EOF
}

MSG_TS=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["ts"])')
MSG_UPDATED=$(printf '%s' "$post_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_updatedAt"])')

cat > "${EXAMPLES_DIR}/messaging/chat-getMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMessage",
    "method": "GET",
    "query": { "msgId": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" ""), "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-react.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.react",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "emoji": ":smile:" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-update.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.update",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "GENERAL", "msgId": "${MSG_ID}", "text": "specmatic test message (edited)" }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" ""), "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-followMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.followMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "mid": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unfollowMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unfollowMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "mid": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-pinMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.pinMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": {
    "status": 200,
    "body": { "message": { "_id": "seed-pin-system-msg", "t": "message_pinned", "rid": "GENERAL", "ts": "${MSG_TS}", "msg": "", "u": { "_id": "${user_id}", "username": "admin", "name": "Administrator" }, "groupable": false, "attachments": [{ "text": "specmatic test message", "author_name": "admin", "author_icon": "/avatar/admin", "ts": "${MSG_TS}", "attachments": [] }], "_updatedAt": "${MSG_UPDATED}" }, "success": true }
  }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unPinMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unPinMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-starMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.starMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-unStarMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.unStarMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-reportMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.reportMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "description": "specmatic test report" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-ignoreUser.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.ignoreUser",
    "method": "GET",
    "query": { "rid": "GENERAL", "userId": "${user_id}", "ignore": "true" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getPinnedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getPinnedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getStarredMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getStarredMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getDiscussions.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getDiscussions",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getMentionedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMentionedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getDeletedMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getDeletedMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL", "since": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

# Enterprise-gated on this (Community Edition) instance -- a real,
# legitimate license-gate response, not a bug. See README. Body has only
# error/success -- this operation's declared 400 schema doesn't include
# errorType (unlike most other operations' 400 schemas), confirmed by
# checking the spec directly after this example was silently dropped at
# load time for including it.
cat > "${EXAMPLES_DIR}/messaging/chat-getMessageReadReceipts-ee.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getMessageReadReceipts",
    "method": "GET",
    "query": { "messageId": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "This is an enterprise feature [error-action-not-allowed]" } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-search.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.search",
    "method": "GET",
    "query": { "roomId": "GENERAL", "searchText": "test" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [$(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" "")] } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getURLPreview.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getURLPreview",
    "method": "GET",
    "query": { "roomId": "GENERAL", "url": "https://rocket.chat" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "urlPreview": { "url": "https://rocket.chat" } } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncMessages",
    "method": "GET",
    "query": { "roomId": "GENERAL", "lastUpdate": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "result": { "updated": [$(msg_body "$MSG_ID" "specmatic test message" "$MSG_TS" "")], "deleted": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-getThreadsList.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getThreadsList",
    "method": "GET",
    "query": { "rid": "GENERAL" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "threads": [$(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" "")], "count": 1, "offset": 0, "total": 1, "success": true } }
}
EOF

REPLY_TS=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["ts"])')
REPLY_UPDATED=$(printf '%s' "$reply_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["message"]["_updatedAt"])')

cat > "${EXAMPLES_DIR}/messaging/chat-getThreadMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.getThreadMessages",
    "method": "GET",
    "query": { "tmid": "${MSG_ID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [$(msg_body "$REPLY_ID" "specmatic thread reply" "$REPLY_TS" "$MSG_ID")] } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncThreadMessages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncThreadMessages",
    "method": "GET",
    "query": { "tmid": "${MSG_ID}", "updatedSince": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": { "update": [$(msg_body "$REPLY_ID" "specmatic thread reply" "$REPLY_TS" "$MSG_ID")], "remove": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-syncThreadsList.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.syncThreadsList",
    "method": "GET",
    "query": { "rid": "GENERAL", "updatedSince": "2020-01-01T00:00:00.000Z" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "threads": { "update": [$(msg_body "$MSG_ID" "specmatic test message (edited)" "$MSG_TS" "")], "remove": [] }, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/chat-sendMessage.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.sendMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "message": { "rid": "GENERAL", "msg": "specmatic sendMessage test" } }
  },
  "http-response": { "status": 200, "body": { "message": $(msg_body "seed-sendmessage" "specmatic sendMessage test" "$MSG_TS" ""), "success": true } }
}
EOF

echo "Wrote messaging.yaml chat.* examples."

# dm.* -- real DM room created above (self-DM, "notes to self" pattern).
cat > "${EXAMPLES_DIR}/messaging/dm-list.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.list",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "ims": [], "offset": 0, "total": 0, "count": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-list-everyone.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.list.everyone",
    "method": "GET",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "ims": [], "offset": 0, "total": 0, "count": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-members.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.members",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "members": [{ "_id": "${user_id}", "name": "Administrator", "username": "admin", "status": "offline", "utcOffset": 0 }], "count": 1, "offset": 0, "total": 1, "success": true } }
}
EOF

# unreadsFrom omitted: the spec declares it type: string, but the real
# app returns null when there's no unread interval (confirmed by direct
# curl) -- a genuine type mismatch (see README), and including it as
# null in our own example fails THIS file's own load-time type-check
# the same way, so it's left out here (not required by the schema).
cat > "${EXAMPLES_DIR}/messaging/dm-counters.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.counters",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "joined": true, "members": 1, "unreads": 0, "msgs": 0, "latest": "${MSG_UPDATED}", "userMentions": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-messages.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.messages",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

# Disabled by default on this instance -- a real, legitimate feature-flag
# response, not a bug. See README.
cat > "${EXAMPLES_DIR}/messaging/dm-messages-others-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.messages.others",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "This endpoint is disabled [error-endpoint-disabled]", "errorType": "error-endpoint-disabled", "details": { "route": "/api/v1/im.messages.others" } } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-history.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.history",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "messages": [], "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-files.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.files",
    "method": "GET",
    "query": { "roomId": "${DM_RID}" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 200, "body": { "files": [], "count": 0, "offset": 0, "total": 0, "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-setTopic.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.setTopic",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}", "topic": "specmatic test topic" }
  },
  "http-response": { "status": 200, "body": { "topic": "specmatic test topic", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-close.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.close",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-open.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.open",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-create.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.create",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "username": "admin" }
  },
  "http-response": { "status": 200, "body": { "room": { "t": "d", "rid": "${DM_RID}", "usernames": ["admin"] }, "success": true } }
}
EOF

# Real, legitimate validation error: blocking requires a second real user
# in the DM room, and this fixture is a self-DM ("notes to self") --
# creating a second real user account is out of scope for this pass, so
# this exercises the real error path rather than a fabricated one.
cat > "${EXAMPLES_DIR}/messaging/im-blockUser-invalidroom.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/im.blockUser",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}", "block": true }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "Invalid room [error-invalid-room]", "errorType": "error-invalid-room" } }
}
EOF

echo "Wrote messaging.yaml dm.* examples."

# autotranslate.* -- disabled workspace-wide on a fresh instance; a real,
# legitimate feature-flag response for all three operations, not a bug.
cat > "${EXAMPLES_DIR}/messaging/autotranslate-getSupportedLanguages-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/autotranslate.getSupportedLanguages",
    "method": "GET",
    "query": { "targetLanguage": "en" },
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "AutoTranslate is disabled." } }
}
EOF

# No example written for autotranslate.saveSettings: confirmed via direct
# curl that the real app returns 400 ("AutoTranslate is disabled.") when
# called on a fresh instance, but the spec only declares 200/401 for this
# operation -- no 400 schema exists at all, so no schema-conformant
# external example is possible without inventing a response shape. This
# is itself the finding (see README) rather than something to work around.

cat > "${EXAMPLES_DIR}/messaging/autotranslate-translateMessage-disabled.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/autotranslate.translateMessage",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "messageId": "${MSG_ID}", "targetLanguage": "es" }
  },
  "http-response": { "status": 400, "body": { "success": false, "error": "AutoTranslate is disabled." } }
}
EOF

echo "Wrote messaging.yaml autotranslate.* examples."

# chat.delete / dm.delete last -- run only after every operation above
# that depends on the message/room still existing.
cat > "${EXAMPLES_DIR}/messaging/chat-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/chat.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "GENERAL", "msgId": "${MSG_ID}" }
  },
  "http-response": { "status": 200, "body": { "_id": "${MSG_ID}", "ts": "${MSG_TS}", "success": true } }
}
EOF

cat > "${EXAMPLES_DIR}/messaging/dm-delete.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/dm.delete",
    "method": "POST",
    "headers": { "X-Auth-Token": "${auth_token}", "X-User-Id": "${user_id}", "Content-Type": "application/json" },
    "body": { "roomId": "${DM_RID}" }
  },
  "http-response": { "status": 200, "body": { "success": true } }
}
EOF

echo "Wrote messaging.yaml chat.delete/dm.delete examples (run last by Specmatic's own scenario ordering, not enforced here)."
