#!/usr/bin/env bash
# Logs into the live RocketChat container as the provisioned admin and
# writes a real authToken/userId into external Specmatic examples that
# need them. RocketChat issues a fresh admin token on every new container,
# so these example files are gitignored and regenerated by this script
# right before a test run -- never committed as static credentials.
#
# Only external example files are touched. authentication.yaml itself is
# never edited -- it declares X-Auth-Token/X-User-Id as plain header
# parameters, and Specmatic's external-examples mechanism
# (https://docs.specmatic.io/features/external_examples) is the
# spec-respecting way to supply concrete values for those headers.
set -euo pipefail

BASE_URL="${RC_BASE_URL:-http://localhost:3000}"
ADMIN_USER="${ADMIN_USERNAME:-admin}"
ADMIN_PASS="${RC_ADMIN_PASS:-SpecmaticAdmin123!}"
EXAMPLES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../examples" && pwd)"

login_response=$(curl -sf -X POST "${BASE_URL}/api/v1/login" \
  -H "Content-Type: application/json" \
  -d "{\"user\":\"${ADMIN_USER}\",\"password\":\"${ADMIN_PASS}\"}")

auth_token=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["authToken"])')
user_id=$(printf '%s' "$login_response" | python3 -c 'import json,sys; print(json.load(sys.stdin)["data"]["userId"])')

if [ -z "$auth_token" ] || [ -z "$user_id" ]; then
  echo "Failed to extract authToken/userId from login response" >&2
  exit 1
fi

# http-response.body here is only used to type-check this example file at
# load time (the actual test assertion compares the LIVE response against
# the spec, not against this body) -- so it's the spec's own declared
# schema shape (copied from authentication.yaml's "User profile" example),
# not a live-captured one. A live-captured body would carry undocumented
# fields (see README "Issues found and fixed") and fail this file's own
# load-time type-check for the same reason those fields fail the real test.
cat > "${EXAMPLES_DIR}/get-me.json" <<EOF
{
  "http-request": {
    "path": "/api/v1/me",
    "method": "GET",
    "headers": {
      "X-Auth-Token": "${auth_token}",
      "X-User-Id": "${user_id}"
    }
  },
  "http-response": {
    "status": 200,
    "body": {
      "_id": "aobEdbYhXfu5hkeqG",
      "name": "Example User",
      "emails": [{ "address": "example@example.com", "verified": true }],
      "status": "offline",
      "statusConnection": "offline",
      "username": "example",
      "utcOffset": 0,
      "active": true,
      "roles": ["user", "admin"],
      "settings": { "preferences": {} },
      "customFields": { "twitter": "@userstwi" },
      "avatarUrl": "http://localhost:3000/avatar/test",
      "success": true
    }
  }
}
EOF

echo "Wrote ${EXAMPLES_DIR}/get-me.json with a live auth token/userId."
